name: .NET Framework Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build 32
      run: MSBuild SuperGrate.sln -t:Restore -t:Rebuild -p:Configuration=Release
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: SuperGrate-x86
        path: |
              .\SuperGrate\bin\Release\SuperGrate.exe
       
    - name: Build 64
      run: MSBuild SuperGrate.sln -t:Restore -t:Rebuild -p:Configuration=Release_64
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: SuperGrate-x64
        path: |
              .\SuperGrate\bin\Release_64\SuperGrate.exe
